routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    send_from_directory,
)
from config import user_file_directory
from models.user import User
from werkzeug.utils import secure_filename
import os.path
from utils import log
from routes import login_required
from routes import current_user

main = Blueprint('index', __name__)


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    u = User.register(form)
    return redirect(url_for('topic.index'))


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('topic.index'))
    else:
        session['user_id'] = u.id
        session.permanent = True
        return redirect(url_for('topic.index'))


@main.route('/profile')
@login_required
def profile():
        u = current_user()
        return render_template('profile.html', user=u)


def allow_file(filename):
    from config import accept_user_file_type
    suffix = filename.split('.')[-1]
    return suffix in accept_user_file_type


# TODO filename应该弄成随机不重复的文件名
@main.route('/addimg', methods=['POST'])
@login_required
def add_img():
    if 'file' not in request.files:
        return redirect(url_for('.profile'))

    file = request.files['file']
    if file.filename == '':
        return redirect(url_for('.profile'))

    if allow_file(file.filename):
        u = current_user()
        filename = secure_filename(file.filename)
        path = os.path.join(user_file_directory, filename)
        file.save(path)
        u.user_image = filename
        u.save()

    return redirect(url_for('.profile'))


@main.route('/uploads/<filename>')
def uploads(filename):
    return send_from_directory(user_file_directory, filename)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="utf-8">

    <title>{% block title %}forum{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">

    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
    {% endblock %}
</head>
<body>
{% block navbar %}
<div class='navbar'>
    <div class='navbar-inner'>
        <div class='container'>
            <a class='brand' href='/'>

                <!--<img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg" />-->

            </a>

            <form id='search_form' class='navbar-search' action="/search">
                <input type='text' id='q' name='q' class='search-query span3' value=''/>
            </form>
            <ul class='nav pull-right'>
                <li><a href="{{ url_for('topic.index') }}">首页</a></li>

                <li><a href='/getstart'>新手入门</a></li>
                <li><a href='/api'>API</a></li>

                <li><a href="/about" target="">关于</a></li>


                <li><a href="{{ url_for('index.index') }}">注册</a></li>
                <li><a href="{{ url_for('index.index') }}">登录</a></li>

            </ul>
            <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
        </div>
    </div>
</div>
{% endblock %}

{% block my_content %}
{% endblock my_content %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>forum</title>
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/index.css">
    <script src="//cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-login">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <form id="login-form" action="{{ url_for('.login') }}" method="post" role="form"
                                  style="display: block;">
                                <h2>登录</h2>
                                <div class="form-group">
                                    <input type="text" name="username" id="username" tabindex="1" class="form-control"
                                           placeholder="用户名" value="">
                                </div>
                                <div class="form-group">
                                    <input type="password" name="password" id="password" tabindex="2"
                                           class="form-control" placeholder="密码">
                                </div>
                                <div class="col-xs-6 form-group pull-left checkbox">
                                    <input id="checkbox1" type="checkbox" name="remember">
                                    <label for="checkbox1">Remember Me</label>
                                </div>
                                <div class="col-xs-6 form-group pull-right">
                                    <input type="submit" name="login-submit" id="login-submit" tabindex="4"
                                           class="form-control btn btn-login" value="登录">
                                </div>
                            </form>
                            <form id="register-form" action="{{ url_for('.register') }}" method="post" role="form"
                                  style="display: none;">
                                <h2>注册</h2>
                                <div class="form-group">
                                    <input type="text" name="username" id="username" tabindex="1" class="form-control"
                                           placeholder="用户名" value="">
                                </div>
                                <div class="form-group">
                                    <input type="email" name="email" id="email" tabindex="1" class="form-control"
                                           placeholder="电子邮件" value="">
                                </div>
                                <div class="form-group">
                                    <input type="password" name="password" id="password" tabindex="2"
                                           class="form-control" placeholder="密码">
                                </div>
                                <div class="form-group">
                                    <input type="password" name="confirm-password" id="confirm-password" tabindex="2"
                                           class="form-control" placeholder="确认密码">
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="register-submit" id="register-submit"
                                                   tabindex="4" class="form-control btn btn-register" value="现在注册">
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6 tabs">
                            <a href="#" class="active" id="login-form-link">
                                <div class="login">登录</div>
                            </a>
                        </div>
                        <div class="col-xs-6 tabs">
                            <a href="#" id="register-form-link">
                                <div class="register">注册</div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function() {
        $('#login-form-link').click(function(e) {
    	    $("#login-form").delay(100).fadeIn(100);
 		    $("#register-form").fadeOut(100);
		    $('#register-form-link').removeClass('active');
		    $(this).addClass('active');
		    e.preventDefault();
	});
	$('#register-form-link').click(function(e) {
		$("#register-form").delay(100).fadeIn(100);
 		$("#login-form").fadeOut(100);
		$('#login-form-link').removeClass('active');
		$(this).addClass('active');
		e.preventDefault();
	});

});
</script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
</head>
<body>
    <h1>用户资料页面</h1>
    <div>
        {{ user.id }}
    </div>
    <div>
        {{ user.name }}
    </div>
    <div>
        {{ user.password }}
    </div>
    <h1>Upload new File</h1>
    <form method=post action="{{ url_for('.add_img') }}" enctype="multipart/form-data">
    <p><input type="file" name="file">
         <input type="submit" value="Upload">
    </p>
    </form>
</body>
</html>