models/topic.py
import json
from models import Model
import time


class Cache(object):

    def get(self, key):
        pass

    def set(self, key, value):
        pass


class MemoryCache(Cache):

    def __init__(self):
        self.cache = {}

    def get(self, key):
        return self.cache[key]

    def set(self, key, value):
        self.cache[key] = value


class RedisCache(Cache):
    import redis
    redis_db = redis.StrictRedis(host='localhost', port=6379, db=0)

    def get(self, key):
        return RedisCache.redis_db.get(key)

    def set(self, key, value):
        return RedisCache.redis_db.set(key, value)


class Topic(Model):
    # TODO 置顶功能，增加一个字段
    __fields__ = Model.__fields__ + [
        ('views', int, 0),
        ('title', str, ''),
        ('content', str, ''),
        ('user_id', int, -1),
        ('board_id', int, -1),
        ('last_reply_time', int, 0),
    ]

    should_update_all = True

    cache = RedisCache()
    # cache = MemoryCache()

    def save(self):
        super(Topic, self).save()
        Topic.should_update_all = True

    def to_dict(self):
        d = {}
        for k in Topic.__fields__:
            key = k[0]
            if not key.startswith('_'):
                d[key] = getattr(self, key)
        return d

    @classmethod
    def from_dict(cls, d):
        instance = cls()
        for k, v in d.items():
            setattr(instance, k, v)
        return instance

    @classmethod
    def all_delay(cls):
        time.sleep(3)
        return Topic.all()

    @classmethod
    def cache_all(cls):
        if Topic.should_update_all:
            # 模拟调用all时有延迟的情况
            # Topic.cache.set('topic_all', json.dumps([i.to_json() for i in cls.all_delay()]))
            l = [i.to_dict() for i in cls.all()]
            Topic.cache.set('topic_all', json.dumps(l))
            Topic.should_update_all = False
        j = Topic.cache.get('topic_all').decode('utf-8')
        l = [Topic.from_dict(i) for i in json.loads(j)]
        return l

    @classmethod
    def get(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def replies(self):
        from .reply import Reply
        r = Reply.find_all(topic_id=self.id)
        return r

    def board(self):
        from .board import Board
        b = Board.find(self.board_id)
        return b

    def user(self):
        from .user import User
        u = User.find(id=self.user_id)
        return u

    def set_last_reply_time(self):
        self.last_reply_time = self.created_time
        self.save()

routes/reply.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.reply import Reply
from models.topic import Topic
from utils import log

main = Blueprint('reply', __name__)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    u = current_user()
    log(u)
    if u is not None:
        r = Reply.new(form, user_id=u.id)
        t = Topic.find(r.topic_id)
        t.last_reply_time = r.created_time
        t.save()
        return redirect(url_for('topic.detail', id=r.topic_id))
    else:
        return redirect(url_for('index.index'))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from utils import log

from routes import current_user
from routes import login_required

from models.topic import Topic
from models.board import Board
from models.user import User


main = Blueprint('topic', __name__)


@main.route('/')
def index():
    args = request.args
    board_id = int(args.get('board_id', -1))
    if board_id == -1:
        # ms = Topic.all()
        ts = Topic.cache_all()
    else:
        ts = Topic.find_all(board_id=board_id)
    bs = Board.all()
    return render_template('topic/index.html', ts=ts, bs=bs)


@main.route('/<int:id>')
def detail(id):
    t = Topic.get(id)
    b = Board.find(t.board_id)
    u = User.find(t.user_id)
    return render_template('/topic/detail.html', topic=t, board=b, user=u)


@main.route('/add', methods=['POST'])
@login_required
def add():
    form = request.form
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    m.set_last_reply_time()
    return redirect(url_for('.detail', id=m.id))


@main.route('/new')
@login_required
def new():
    bs = Board.all()
    return render_template('topic/new.html', bs=bs)

templates/topic/detail.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
    <script src="//cdn.bootcss.com/marked/0.3.6/marked.min.js"></script>
{% endblock %}
{% block my_content %}

<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                {{ topic.created_time | format }}
            </span>
                    <span>
                作者
                <a href="/user/{{ user.username }}">{{ user.username }}</a>
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                        <!--{% set s = url_for('topic.index') + '?board_id=' + board.id | string %}-->
                    <!--来自 <a href={{s}}>{{ board.name }}</a>-->
                来自 <a href="/topic?board_id={{ board.id }}">{{ board.name }}</a>
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">
                        {{ markdown.markdown(topic.content) | safe }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
        <div class='cell reply_area reply_item'>
            <div class='author_content'>
                <a href="/user/leiwei1991" class="user_avatar">
                    <img src="https://avatars2.githubusercontent.com/u/10721874?v=3&amp;s=120"
                         title="{{ r.user().username }}"/>
                </a>
                <div class='user_info'>
                    <a class='dark reply_author'>
                        {{ r.user().username }}
                    </a>
                    <a class="reply_time">
                        <!--{{ loop.index }}楼 • 2 天前-->
                        {{ loop.index }}楼 •  {{ r.created_time | delta }}
                    </a>
                </div>
                <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                </div>
            </div>
            <div class='reply_content from-leiwei1991'>
                <div class="markdown-text">
                    {{ markdown.markdown(r.content) | safe }}
                </div>
            </div>
        </div>
        {% endfor %}
        <div>
            <form action="{{ url_for('reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea class="reply_content" name="content"></textarea>
                <button>添加回复</button>
            </form>
        </div>
        <div id="preview"></div>
    </div>
</div>
<script>
    $(".reply_content").on('input', function() {
        text = $(this).val()
        marked_text = marked(text)
        $("#preview").html(marked_text)
    });
</script>

{% endblock my_content %}

templates/topic/index.html
{% extends 'base.html' %}

{% block my_content %}

<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="inner">
                <a href="/topic/new" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="{{ url_for('topic.index') }}"
                   class="topic-tab current-tab">
                    全部
                </a>

                {% for b in bs %}
                <a href="/topic?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.name }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ts %}
                    <div class='cell'>
                        <a class="user_avatar pull-left" href="user/username">
                            <img src="{{ '/uploads/' + t.user().user_image + '?v=3&amp;s=120' }}"
                                 title="{{ t.user().username }}"/>
                        </a>

                        <span class="reply_count pull-left">
                            <span class="count_of_replies" title="回复数">{{ t.replies() | count }}</span>
                            <span class="count_seperator">/</span>
                            <span class="count_of_visits" title='点击数'>{{ t.views }}</span>
                        </span>

                        <a class='last_time pull-right' href="{{ url_for('topic.detail', id=t.id) }}">
                            <img class="user_small_avatar"
                                 src="https://avatars3.githubusercontent.com/u/20496444?v=3&amp;s=120">
                            <span class="last_active_time">{{ t.last_reply_time | delta }}</span>
                        </a>

                        <div class="topic_title_wrapper">
                            <!--<span class='put_top'>置顶</span>-->
                            <a class='topic_title' href="{{ url_for('topic.detail', id=t.id) }}" title="{{ t.title }}">
                                {{ t.title }}
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock my_content %}

templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>

    <script src="//cdn.bootcss.com/marked/0.3.6/marked.min.js"></script>
</head>
<body>
<div id="main">
    <div id="content">
        <div class="panel">
            <div class="inner post">
                <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
                        <span class="tab-selector">选择板块：</span>
                        <select name="board_id" id="board" required>
                            <option value="">请选择</option>
                            {% for b in bs %}
                            <option value="{{ b.id }}">{{ b.name }}</option>
                            {% endfor %}
                        </select>
                        <div class='markdown_editor in_editor'>
                            <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20'
                                          placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                    <input type="submit" class='span-primary submit_btn' data-loading-text="提交中"
                                           value="提交">
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
<div id="preview"></div>
<script>
    $(".editor").on('input', function() {
        text = $(this).val()
        marked_text = marked(text)
        $("#preview").html(marked_text)
    });
</script>
</body>
</html>

templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>